### ISSUE TITLE
Matomo-Instanz unseres FTP-Servers hinzufügen

### ISSUE THREAD

**Issue by tlorusso** [statistikZH/statZHmatomo#10]
Matomo-Instanz des FTP-Servers hinzufügen um die Downloadstatistiken unserer OGD / Daten auf zh.ch (auch wiederkehrende Direktdownloads) beziehen zu können:

https://web-analytics-test.labs.abraxas.ch/

**Comment by ruizcrp** [comment]
FTP-Instanz wurde hinzugefügt und funktioniert lokal (für R-Server schauen wir noch).
