### ISSUE TITLE
Add arguments to read_matomo_data.R to enable value "range" in period argument 

### ISSUE THREAD

**Issue by larnsce** [statistikZH/statZHmatomo#11]
See here for reference under API Request -> Standard API parameters:

https://developer.matomo.org/api-reference/reporting-api

- period — the period you request the statistics for. Can be any of: day, week, month, year or range. All reports are returned for the dates based on the website's time zone.

- day returns data for a given day.
- week returns data for the week that contains the specified 'date'
- month returns data for the month that contains the specified 'date'
- year returns data for the year that contains the specified 'date'
- range returns data for the specified 'date' range.

For example to request a report for the range Jan 1st to Feb 15th you would write **&period=range&date=2011-01-01,2011-02-15**

**Comment by ruizcrp** [comment]
Parameters for period and date are now working
