### ISSUE TITLE
Add "flatten_report = TRUE/FALSE" argument to read_matomo_data() to control CSV data input 

### ISSUE THREAD

**Issue by larnsce** [statistikZH/statZHmatomo#12]
The function needs to be extended by one argument:

- flatten_report = TRUE/FALSE (default TRUE for "format = CSV")

And the URL paster expanded for:

- flat = 1 (default for "format = CSV") 

https://sa.abx-net.net/index.php?date=2020-07-26&filter_limit=10&**flat=1**&force_api_session=1&format=CSV&idDimension=1&idSite=4&language=en&method=CustomDimensions.getCustomDimension&module=API&period=month&reportUniqueId=CustomDimensions_getCustomDimension_idDimension--1&segment=&token_auth=TOKEN_AUTH&translateColumnNames=1

**Comment by ruizcrp** [comment]
Parameters for flat and expanded were added. Closed.
